network:
    ethernets:
        enp0s3:
            addresses:
            - 192.168.55.11/24
            dhcp6: false
            routes:
            - to: default
              via: 192.168.1.1
            nameservers:
                addresses:
                - 8.8.4.4
                - 8.8.8.8
                search: []
            optional: true
    version: 2
